GET http://localhost:3001/api/users/ HTTP/1.1
Content-Type: application/json
###

POST http://localhost:3001/api/users/ HTTP/1.1
Content-Type: application/json

{
    "username": "onald",
    "email": "Firbank@mail.ru",
    "password": "password123"
} 
###

PUT http://localhost:3001/api/users/1 HTTP/1.1
Content-Type: application/json

{
    "password": "password123321"
} 